### ISSUE TITLE
Agregar página "consultar material"

### ISSUE THREAD

**Issue by SandroPastorini** [juanfrvera/Libreria#3]
**[E-CU02: Consultar material](
https://docs.google.com/document/d/1PjYZ9fKTXpLWuvC06FWj7BmuCOMxyQLtg6sUFN78N7w/edit)**
Debería mostrar los siguientes campos (todos texto, sólo lectura):
- [ ] Título
- [ ] Autores
- [ ] ISBN/ISSN
- [ ] Proveedor
- [ ] Edición
- [ ] Retención
- [ ] Stock
- [ ] Cantidad

Botones
- [ ] Botón para agregar al carrito
- [ ] Cancelar

**Comment by juanfrvera** [comment]
Página para ver material creada
